name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        build_configuration: [Release Unicode, Debug Unicode]
        build_platform: [x64, Win32, ARM64]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild of plugin dll
      working-directory: VC\
      run: msbuild TextFX.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v143"

    - uses: olegtarasov/get-tag@v2.1.4
      id: tagName

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release Unicode'
      uses: actions/upload-artifact@v4
      with:
          name: NppTextFX2_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
          path: VC\NppTextFX64.dll

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_platform == 'Win32' && matrix.build_configuration == 'Release Unicode'
      uses: actions/upload-artifact@v4
      with:
          name: NppTextFX2_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
          path: VC\NppTextFX.dll

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_platform == 'ARM64' && matrix.build_configuration == 'Release Unicode'
      uses: actions/upload-artifact@v4
      with:
          name: NppTextFX2_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
          path: VC\${{ matrix.build_platform }}\${{ matrix.build_configuration }}\NppTextFX64.dll

    - name: Create release on tagging
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: NppTextFX2_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}

